### ISSUE TITLE
have a problem

### ISSUE THREAD

**Issue by zhengyuezhi** [hrhodin/UnsupervisedGeometryAwareRepresentationLearning#1]
Hello, I ran the model you provided and the python configs/test_encodeDecode.py statement, but an error occurred, prompting
Loading weights from config_dict['pretrained_network_path']
./examples/network_best_val_t1.pth
Traceback (most recent call last):
  File "configs/test_encodeDecode.py", line 175, in <module>
    Ignite.run(config_dict_module.__file__, config_dict)
  File "configs/test_encodeDecode.py", line 42, in run
    Model = self.load_network(config_dict)
  File "/home/UnsupervisedGeometryAwareRepresentationLearning/configs/train_encodeDecode.py", line 177, in load_network
    Pretrained_states = torch.load(pretrained_network_path)
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 303, in load
    Return _load(f, map_location, pickle_module)
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 476, in _load
    Deserialized_objects[key]._set_from_file(f, offset, f_is_real_file)
RuntimeError: unexpected EOF. The file might be corrupted.

I don't know if there is a problem with the network_best_val_t1.pth you provided. Can you help me re-upload it? Thank you.

**Comment by hrhodin** [comment]
Thanks for reporting the problem.

Can you try replacing the network_best_val_t1.pth with the one at
"http://documents.epfl.ch/groups/c/cv/cvlab-unit/www/data/ECCV2018Rhodin/network_best_val_t1.pth"

I fixed the code to download from the appropriate link. Deleting network_best_val_t1.pth and executing the new version should work too. Does it?

**Comment by hrhodin** [comment]
Seems to be fixed.
